apiVersion: v1
kind: Secret
metadata:
  name:  mongo-secret
data:
   mongodbUser: YWRtaW5kYg==
   mongodbPass: YWRtaW4xMjM0NQ==         #Never use @ in the password as it is inbuilt character in URL
type: Opaque