apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-database
  template:
    metadata:
      labels:
        app: mongo-database
    spec:
      containers:
        - name: mongo-image
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME    #parameters taken from mongo-express docker image from docker hub
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongodbUser
            - name: MONGO_INITDB_ROOT_PASSWORD    #parameters taken from mongo-express docker image from docker hub
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongodbPass
---                                                #Used to for separating two yaml files as service is created with deployment it is a standard practice
kind: Service
apiVersion: v1
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo-database
  ports:
    - name: mongo-ports
      port: 27017
      targetPort: 27017
