apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express-image
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME   #parameters taken from mongo-express docker image from docker hub
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongodbUser
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD   #parameters taken from mongo-express docker image from docker hub
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongodbPass
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: mongoUrl

---
kind: Service
apiVersion: v1
metadata:
  name: mongo-express-service
spec:
  selector:
    app:  mongo-express
  type:  LoadBalancer
  ports:
  - name:  mongo-express-port
    port:  8081                           # match with container port
    targetPort: 8081
    nodePort: 30000                        #Range for port 30000-32767 