apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-label
  template:
    metadata:
      labels: 
        app: nginx-label
    spec:
      containers:
      - name: nginx-image
        image: nginx
        ports:
        - containerPort: 8080