apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"nginx-deployment","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"nginx-label"}},"template":{"metadata":{"labels":{"app":"nginx-label"}},"spec":{"containers":[{"image":"nginx","name":"nginx-image","ports":[{"containerPort":8080}]}]}}}}
  creationTimestamp: "2021-09-22T17:16:13Z"
  generation: 1
  name: nginx-deployment
  namespace: default
  resourceVersion: "674"
  uid: 2bc5c532-cf43-42d1-a52e-43a3e48e8472
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-label
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-label
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx-image
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2021-09-22T17:16:50Z"
    lastUpdateTime: "2021-09-22T17:16:50Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-09-22T17:16:13Z"
    lastUpdateTime: "2021-09-22T17:16:50Z"
    message: ReplicaSet "nginx-deployment-5cf884db4d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
